# 公共配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  address: 0.0.0.0
  port: 9003
  servlet:
    context-path: /api/interfaceServer
spring:
  application:
    name: glory-api-interface-server
  # 支持 swagger3（springfox）
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
