# 公共配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  address: 0.0.0.0
  port: 9009
  # 支持 swagger3（springfox）
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      routes:
        - id: rule1
          uri: http://127.0.0.1:9003
          predicates:
            - Path=/api/interface/**
  redis:
    database: 1
    host: 192.168.100.100
    port: 3697
    timeout: 5000
    password: hry99120805
dubbo:
  application:
    qosEnable: false
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 29009
  registry:
    address: nacos://localhost:8848

rocketmq:
  name-server: 192.168.100.100:9876
  producer:
    group: gateway-interface
    send-message-timeout: 30000